### ISSUE TITLE
Access to non existing boards

### ISSUE THREAD

**Issue by akshatgit** [andrew-bbq/BoardSpace#7]
Summary:
I can access any board by changing the code here: http://www.boardspace.us/board?code=MDKF

Description:
I created a board and received the MDKF code for it. When I tried to access a board with code "1234", I received error on the home page. But if I go to http://www.boardspace.us/board?code=1234, I can see a board. 

Severity:
High

**Comment by arshadmhabib** [comment]
**Another issue I found which is related to this original issue:** When I tried to type an existing or non-existing board link with http://www.boardspace.us/board?code=SIP5 in incognito window, I get the below stack trace which shouldn't be disclosed to any ordinary user.

Cannot read property 'SIP5' of undefined
TypeError: Cannot read property 'SIP5' of undefined
    at /var/app/current/routes/index.js:109:34
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/app/current/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/app/current/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at /var/app/current/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:335:12)
    at next (/var/app/current/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/var/app/current/node_modules/express/lib/router/index.js:174:3)
    at router (/var/app/current/node_modules/express/lib/router/index.js:47:12)
